import { EmptyState } from "@/components/common/EmptyState";
import type { BacktestTrade } from "@/lib/api/types";
import { formatDateTime, formatPercent, formatPrice } from "@/lib/format";

export function TradeTable({ trades }: { trades: BacktestTrade[] }) {
  if (!trades.length) {
    return <EmptyState message="No trades were generated by this backtest." />;
  }

  return (
    <div className="overflow-x-auto">
      <table className="w-full min-w-[900px] text-left text-sm">
        <thead className="border-b text-xs uppercase text-muted-foreground">
          <tr>
            <th className="py-3 pr-4">Entry</th>
            <th className="py-3 pr-4">Exit</th>
            <th className="py-3 pr-4">Side</th>
            <th className="py-3 pr-4">Entry Price</th>
            <th className="py-3 pr-4">Exit Price</th>
            <th className="py-3 pr-4">Fees</th>
            <th className="py-3 pr-4">Slippage</th>
            <th className="py-3 pr-4">PnL</th>
            <th className="py-3 pr-4">Exit Reason</th>
          </tr>
        </thead>
        <tbody>
          {trades.map((trade, index) => (
            <tr className="border-b last:border-0" key={`${trade.entry_time}-${index}`}>
              <td className="py-3 pr-4">{formatDateTime(trade.entry_time)}</td>
              <td className="py-3 pr-4">{formatDateTime(trade.exit_time)}</td>
              <td className="py-3 pr-4 capitalize">{trade.side}</td>
              <td className="py-3 pr-4">{formatPrice(trade.entry_price)}</td>
              <td className="py-3 pr-4">{formatPrice(trade.exit_price)}</td>
              <td className="py-3 pr-4">{formatPrice(trade.fee)}</td>
              <td className="py-3 pr-4">{formatPrice(trade.slippage)}</td>
              <td className="py-3 pr-4">
                {formatPrice(trade.pnl)} ({formatPercent(trade.pnl_pct)})
              </td>
              <td className="py-3 pr-4">{trade.exit_reason.replaceAll("_", " ")}</td>
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  );
}
