import { render, screen } from "@testing-library/react";
import { describe, expect, it } from "vitest";

import { TradeTable } from "@/components/backtesting/TradeTable";
import type { BacktestTrade } from "@/lib/api/types";

const trade: BacktestTrade = {
  symbol: "BTC/USDT",
  side: "long",
  entry_time: "2025-01-01T00:00:00Z",
  entry_price: 100,
  exit_time: "2025-01-02T00:00:00Z",
  exit_price: 110,
  quantity: 1,
  notional: 100,
  fee: 1,
  slippage: 0.5,
  pnl: 9,
  pnl_pct: 9,
  holding_period_bars: 24,
  exit_reason: "end_of_backtest"
};

describe("TradeTable", () => {
  it("renders trades", () => {
    render(<TradeTable trades={[trade]} />);
    expect(screen.getByText("long")).toBeInTheDocument();
    expect(screen.getByText("end of backtest")).toBeInTheDocument();
  });

  it("renders empty state", () => {
    render(<TradeTable trades={[]} />);
    expect(screen.getByText("No trades were generated by this backtest.")).toBeInTheDocument();
  });
});
